// TIMELOOP — Level-Definitionen
// Grid-basierte Räume. Koordinaten sind Zellen (x,y), (0,0) = oben links.
// Jede Aktion (Bewegung / Interagieren / Warten) des Spielers verbraucht genau 1 Tick.

const LEVELS = [
  {
    id: 1,
    chapter: 1,
    name: "Erste Schritte",
    hint: "Bewege dich zum Ausgang. Ein Schalter öffnet die Tür.",
    cols: 6, rows: 8,
    timelineLength: 16,
    playerStart: { x: 2, y: 6 },
    walls: [
      "0,0","1,0","2,0","3,0","4,0","5,0",
      "0,1","5,1",
      "0,2","5,2",
      "0,3","1,3","3,3","4,3","5,3",
      "0,4","5,4",
      "0,5","5,5",
      "0,6","5,6",
      "0,7","1,7","2,7","3,7","4,7","5,7",
    ],
    goal: { x: 2, y: 1 },
    switches: [{ id: "sw1", x: 3, y: 4, manual: false }],
    doors: [{ id: "d1", x: 2, y: 3, requires: { type: "switches", ids: ["sw1"] } }],
    keys: [],
    boxes: [],
    npc: null,
    bonus: ["Löse das Level ohne Reset.", "Weniger als 10 Aktionen."],
  },
  {
    id: 2,
    chapter: 1,
    name: "Der Schlüssel",
    hint: "Die Tür ist verschlossen. Reise zurück und nimm den Schlüssel, bevor die Wache ihn holt.",
    cols: 7, rows: 7,
    timelineLength: 20,
    playerStart: { x: 1, y: 5 },
    walls: [
      "0,0","1,0","2,0","3,0","4,0","5,0","6,0",
      "0,6","1,6","2,6","3,6","4,6","5,6","6,6",
      "0,1","0,2","0,3","0,4","0,5",
      "6,1","6,2","6,3","6,4","6,5",
      "1,2","2,2","3,2","4,2",
    ],
    goal: { x: 5, y: 1 },
    switches: [],
    doors: [{ id: "d1", x: 5, y: 2, requires: { type: "key", keyId: "k1" } }],
    keys: [{ id: "k1", x: 3, y: 3 }],
    boxes: [],
    npc: {
      id: "npc1",
      start: { x: 5, y: 4 },
      // dx,dy pro Tick; bei "action":"interact" versucht die Wache den Schlüssel zu nehmen
      moves: [
        { dx: 0, dy: 0 }, { dx: 0, dy: 0 }, { dx: -1, dy: 0 }, { dx: -1, dy: 0 },
        { dx: 0, dy: -1 }, { action: "interact" },
      ],
    },
    bonus: ["Löse das Level ohne Reset.", "Maximal 2 Zeitreisen."],
  },
  {
    id: 3,
    chapter: 2,
    name: "Die Kiste",
    hint: "Die Kiste ist zu schwer für die Tür. Schiebe sie auf die Druckplatte, damit der Weg zum Ausgang frei wird.",
    cols: 7, rows: 8,
    timelineLength: 22,
    playerStart: { x: 1, y: 6 },
    walls: [
      "0,0","1,0","2,0","3,0","4,0","5,0","6,0",
      "0,1","6,1",
      "0,2","6,2",
      "0,3","1,3","2,3","4,3","5,3","6,3",
      "0,4","6,4",
      "0,5","6,5",
      "0,6","6,6",
      "0,7","1,7","2,7","3,7","4,7","5,7","6,7",
    ],
    goal: { x: 3, y: 1 },
    switches: [],
    doors: [{ id: "dGap", x: 3, y: 3, requires: { type: "boxOn", boxId: "b1", plateX: 1, plateY: 5 } }],
    keys: [],
    // Kiste steht bei (4,5) und muss 3 Felder nach links auf die Druckplatte (1,5)
    // geschoben werden, damit sich die Lücke in der Trennwand (3,3) öffnet.
    boxes: [{ id: "b1", x: 4, y: 5 }],
    npc: null,
    bonus: ["Löse das Level ohne Reset.", "Maximal 6 Schiebe-Aktionen."],
  },
  {
    id: 4,
    chapter: 3,
    name: "Zwei Schalter",
    hint: "Beide Schalter müssen gleichzeitig aktiv sein. Aktiviere den ersten, reise zurück — dein vergangenes Ich wiederholt den Weg — und aktiviere selbst den zweiten.",
    cols: 7, rows: 7,
    timelineLength: 24,
    playerStart: { x: 3, y: 5 },
    walls: [
      "0,0","1,0","2,0","3,0","4,0","5,0","6,0",
      "0,6","1,6","2,6","3,6","4,6","5,6","6,6",
      "0,1","0,2","0,3","0,4","0,5",
      "6,1","6,2","6,3","6,4","6,5",
      "1,2","2,2","4,2","5,2",
    ],
    goal: { x: 3, y: 1 },
    switches: [
      { id: "swA", x: 1, y: 3, manual: false },
      { id: "swB", x: 5, y: 3, manual: false },
    ],
    doors: [{ id: "d1", x: 3, y: 2, requires: { type: "switches", ids: ["swA", "swB"] } }],
    keys: [],
    boxes: [],
    npc: null,
    bonus: ["Löse das Level mit nur einer Zeitkopie.", "Maximal 1 Reset."],
  },
  {
    id: 5,
    chapter: 3,
    name: "Kettenschluss",
    hint: "Schiebe die Kiste aus dem Weg, aktiviere den Schalter, hole den Schlüssel und öffne die zweite Tür.",
    cols: 8, rows: 8,
    timelineLength: 28,
    playerStart: { x: 1, y: 6 },
    walls: [
      "0,0","1,0","2,0","3,0","4,0","5,0","6,0","7,0",
      "0,7","1,7","2,7","3,7","4,7","5,7","6,7","7,7",
      "0,1","0,2","0,3","0,4","0,5","0,6",
      "7,1","7,2","7,3","7,4","7,5","7,6",
      "4,1","4,3","4,4","4,5","4,6",
      "2,4","3,4","2,5","3,5","2,6","3,6",
      "5,1",
    ],
    goal: { x: 6, y: 1 },
    switches: [{ id: "swHold", x: 1, y: 3, manual: false }],
    doors: [
      { id: "dGate", x: 4, y: 2, requires: { type: "switches", ids: ["swHold"] } },
      { id: "dMain", x: 6, y: 2, requires: { type: "key", keyId: "k1" } },
    ],
    keys: [{ id: "k1", x: 5, y: 3 }],
    boxes: [{ id: "b1", x: 1, y: 5 }],
    npc: null,
    bonus: ["Löse das Level ohne Reset.", "Weniger als 25 Aktionen."],
  },
  {
    id: 6,
    chapter: 3,
    name: "Die Schleife",
    hint: "Drei Schalter, ein Ausgang. Du brauchst mehrere Versionen deiner selbst.",
    cols: 7, rows: 7,
    timelineLength: 30,
    playerStart: { x: 3, y: 5 },
    walls: [
      "0,0","1,0","2,0","3,0","4,0","5,0","6,0",
      "0,6","1,6","2,6","3,6","4,6","5,6","6,6",
      "0,1","0,2","0,3","0,4","0,5",
      "6,1","6,2","6,3","6,4","6,5",
      "1,2","2,2","4,2","5,2",
    ],
    goal: { x: 3, y: 1 },
    switches: [
      { id: "swA", x: 1, y: 4, manual: false },
      { id: "swB", x: 5, y: 4, manual: false },
      { id: "swC", x: 3, y: 3, manual: false },
    ],
    doors: [{ id: "d1", x: 3, y: 2, requires: { type: "switches", ids: ["swA", "swB", "swC"] } }],
    keys: [],
    boxes: [],
    npc: null,
    bonus: ["Löse das Level mit genau 2 Zeitkopien.", "Maximal 2 Resets."],
  },
];
